# Generated by Django 5.2.6 on 2025-10-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.sport'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slotlock',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='slotlock',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.sport'),
        ),
        migrations.AddField(
            model_name='slotlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='bookings.slotlock'),
        ),
        migrations.AddField(
            model_name='slotwaitlist',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='slotwaitlist',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.sport'),
        ),
        migrations.AddField(
            model_name='slotwaitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlisted_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='slotlock',
            index=models.Index(fields=['expires_at'], name='slot_locks_expires_3a181a_idx'),
        ),
        migrations.AddIndex(
            model_name='slotlock',
            index=models.Index(fields=['is_converted'], name='slot_locks_is_conv_e7e3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='slotlock',
            index=models.Index(fields=['user', 'is_converted'], name='slot_locks_user_id_2e5625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slotlock',
            unique_together={('club', 'sport', 'date', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_user_id_1eeb34_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'club'], name='bookings_date_0363f6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'date'], name='bookings_status_89e2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='slotwaitlist',
            index=models.Index(fields=['club', 'sport', 'date', 'start_time'], name='slot_waitli_club_id_0d70e8_idx'),
        ),
        migrations.AddIndex(
            model_name='slotwaitlist',
            index=models.Index(fields=['notified', 'created_at'], name='slot_waitli_notifie_5714ea_idx'),
        ),
    ]
