# Generated by Django 5.2.6 on 2026-08-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='bookings.slotlock'),
        ),
    ]
