# Generated by Django 5.2.6 on 2025-09-16 15:24

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('sports_available', models.JSONField(default=list)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('images', models.JSONField(default=list)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('facilities', models.JSONField(default=list)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('amenities', models.JSONField(default=list)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('advance_booking_days', models.IntegerField(default=7)),
            ],
            options={
                'db_table': 'clubs_sportsclub',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClubReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.sportsclub')),
            ],
            options={
                'db_table': 'clubs_clubreview',
                'ordering': ['-created_at'],
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('swimming', 'Swimming'), ('cricket', 'Cricket'), ('volleyball', 'Volleyball')], max_length=50)),
                ('max_capacity', models.IntegerField(default=1)),
                ('current_bookings', models.IntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='clubs.sportsclub')),
            ],
            options={
                'db_table': 'clubs_timeslot',
                'ordering': ['date', 'start_time'],
                'unique_together': {('club', 'date', 'start_time', 'sport')},
            },
        ),
    ]
