# Generated by Django 5.2.6 on 2026-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_sport_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
