# Generated by Django 5.2.6 on 2026-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
