# Generated by Django 5.2.6 on 2026-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
