# Generated by Django 5.2.6 on 2026-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
